= Writing JS posts with JBake : React JS
@marioggar
2018-11-12
:jbake-type: post
:jbake-status: published
:jbake-tags: js, react, jbake
:sources: ../../../../assets/js/2018/11/
:scripts: https://unpkg.com/react@16/umd/react.development.js|https://unpkg.com/react-dom@16/umd/react-dom.development.js|js/2018/11/react.js
:css: css/2018/11/react.css
:idprefix:

== Intro

In this second entry about adding JS programming entries to JBake
posts I've included a typical React TODO item example

WARNING: The JS example I'm using here is just a quick draft just to
show how to include JS and CSS code in a post entry. Don't take it too
seriosly.

=== Add required resources

To be able to work with react, and load the example script, I need to add the `scripts` attribute in the post header:

[source, adoc]
----
:scripts: https://unpkg.com/react@16/umd/react.development.js|https://unpkg.com/react-dom@16/umd/react-dom.development.js|js/2018/11/react.js
----

Basically, I've included the `react`, `react-dom` libraries at the
header of the document, and then the example dependency inside the
blog project's assets `js/2018/11/react.js` . If I would like to add a
custom css, you can add as well a `css` entry in the post header:

[source, adoc]
----
:css: css/2018/11/react.css
----

=== No JSX when using plain JS

Because JSX can't be included through a `<script/>' import, I had to
create a helper function to create new elements.

[source, js]
.helper
----
include::{sources}/react.js[tags=helper,ident=0]
----

=== TodoPanel

[source, js]
.TodoPanel
----
include::{sources}/react.js[tags=TodoPanel,ident=0]
----

<1> Create default state
<2> Sets which is the current item to add
<3> Adds the current item to the tasks list
<4> Deletes the clicked item from the tasks list
<5> renders the tasks panel

=== Creating items

The `TodoItems` component represents the tasks list. It only renders
an `ul` elements containing as many items as tasks found in the task
list.

[source, js]
.TodoItems
----
include::{sources}/react.js[tags=TodoItems,ident=0]
----

Every item of the task list is built using the `TodoItem` component

[source, js]
.TodoItem
----
include::{sources}/react.js[tags=TodoItem,ident=0]
----

=== Render example

Finally, in order to render the `TodoPanel` in this document we need
to link the component with an available dom element.

[source, js]
.Render
----
include::{sources}/react.js[tags=footer,ident=0]
----

=== Result

++++
<div id="like_button_container"></div>
++++

It seems easy to add simple vanilla JS examples to a post. However
trying to create more complex examples would require a proper build
tool such as plain npm scripts or webpack.

=== Resources

- https://reactjs.org/[React]
