= Groovy Switch Case with Closures
@marioggar
2017-03-22
:jbake-type: post
:jbake-status: published
:jbake-tags: groovy, jvm
:idprefix:
:sources: ../../../../../../../sources/2017/03/groovy-switch-case/src/

== Intro
Yesterday I was talking to my dear friend
https://twitter.com/ilopmar[@ilopmar] about his Greach presentation
about Javaslang. It was when we were comparing Javaslang's pattern
matching module vs Groovy's switch case when my Groovy instinct made
me realise how underated Groovy's switch-case statement is, specially
how closures can be applied to Groovy's switch/case statements to
create limited pattern-matching expressions.

NOTE: BTW, Don't get me wrong I think Javaslang is an A-M-A-Z-I-N-G
library, and I've been using it in my projects since the very
beginning. This entry is just a claim to use the full potential of
Groovy's switch case statement.

Let me show you my point. Lets say we have the `Person` type:

[source, groovy]
.Person
----
include::{sources}/main/groovy/pm/Person.groovy[indent=0]
----

The next example shows how to return whether `john` or `carl`
depending on the exact values of the properties contained in the
`Person` object passed as parameter.

[source, groovy]
.Initial case
----
include::{sources}/main/groovy/pm/Example1.groovy[tags=example0,indent=0]
----

We all agree it's a very verbose syntax, and bearing in mind languages
such as Haskell or Scala have already fixed this problem using pattern
matching, why should we suffering this type of syntax ?

Although we don't have a Scala-like pattern matching... yet, we are
clearly underestimating the power of Groovy's switch/case statement.

=== Exact Matching

When trying to figure out which action to take based on properties of
the object passed as parameter, we can trust object identity by
creating an object with the same values.

[source, groovy]
.Exact matching
----
include::{sources}/main/groovy/pm/Example1.groovy[tags=example1a,indent=0]
----

It's true that, by default, we can't omit the new when creating a new object instance,
but, that's just an excuse, we can always create a method with the class name that builds
the instance

[source, groovy]
.Tuple Constructor without `new`
----
include::{sources}/main/groovy/pm/Example1.groovy[tags=Person,indent=0]
----

And then come again with this:

[source, groovy]
.Exact matching
----
include::{sources}/main/groovy/pm/Example1.groovy[tags=example1,indent=0]
----

No magic here, this is just old plain java rules: `equals` and
`hashcode` underneath applied to out class thanks to the `@Canonical`
transformation. But what happens when we would like to get fancy and
match using certain rules over the object's properties ?

=== Pattern matching with closures

In the previous example we were comparing values against values, but
what if we would like to compare values against certain rules or
patterns ? Now what we want is, given a data structure (an object
here), to check if its internal values match a given set of patterns.

With that in mind lets get back to the `Person` example to see if we
can apply certain patterns to the object's properties:

[source, groovy]
.Pattern matching
----
include::{sources}/main/groovy/pm/Example1.groovy[tags=example2,indent=0]
----
<1> Matches any person whose name ends with `arl` and having an age greater than 25
<2> Matches any person whose name ends with `hn` and having an age less than 23
<3> Matches any person with any name and having an age greater than 60
<4> In any other case return `nobody`

Now, How is this working ? Well actually `Person(pattern, pattern)` is
a method returning a `Closure` acting as a `predicate`:

[source, groovy]
.Person w Closure
----
include::{sources}/main/groovy/pm/Example1.groovy[tags=PersonClosures,indent=0]
----

Eventually it will take the person instance to evaluate and it will
execute both patterns with the same value and if both executions are
correct then case expression will succeed.

Let me show you how I built the patterns `any`, `gt`, `lt`, and
`endsWith`:

[source, groovy]
.any
----
include::{sources}/main/groovy/pm/Example1.groovy[tags=any,indent=0]
----

[source, groovy]
.endsWith
----
include::{sources}/main/groovy/pm/Example1.groovy[tags=endsWith,indent=0]
----

[source, groovy]
.gt
----
include::{sources}/main/groovy/pm/Example1.groovy[tags=gt,indent=0]
----

[source, groovy]
.lt
----
include::{sources}/main/groovy/pm/Example1.groovy[tags=lt,indent=0]
----

=== Altogether

Apart from using closures you can also use classes to check whether
the instance evaluated in the `case` case is an instance of that class
or not.

In next example we have the following domain classes:

[source, groovy]
.Mammal
----
include::{sources}/main/groovy/pm/Mammal.groovy[indent=0]
----

`Mammal` uses `@Canonical` which among other things implements
**equals** and **hashCode** methods. And it also uses
`@TupleConstructor` to avoid using a constructor map.

[source, groovy]
.Dog
----
include::{sources}/main/groovy/pm/Dog.groovy[indent=0]
----

Dog inherits `Mammal` constructors.

[source, groovy]
.Cat
----
include::{sources}/main/groovy/pm/Cat.groovy[indent=0]
----

`Cat` also inherits `Mammal` constructors.

Then we would like to be able to match:

- **Types**: The evaluated parameter is of certain type (a Dog, or a Cat, or a Mammal)
- **Values**: The evaluated parameter is a certain value (properties are equal)
- **Patterns**: The evaluated parameter follows certain pattern rules

Having that in mind I came up with the following code:

[source, groovy]
.Pattern matching
----
include::{sources}/main/groovy/pm/Example2.groovy[tags=example0,indent=0]
----
<1> Matches if it is any Dog
<2> Matches if it is a specific Cat
<3> Matches if it is a Cat following certain patterns
<4> Matches if it is any Cat

== A more advance pattern matching in Groovy ?

As I said at the beggining, Groovy's switch/case is not a full pattern
matching solution. I would point out at least the fact that it doesn't
have value destructuring, which is very useful in data structures such
as lists.

The good news is that https://twitter.com/bsideup[Sergei Egorov] wrote
some years ago a library bringing pattern matching to Groovy. I
strongly recommend to check it out. These are some examples of what
can be achieved with this library:

- https://github.com/bsideup/groovy-pattern-match/blob/feature/dsl-like-matching/src/test/groovy/ru/trylogic/groovy/pattern/PatternMatchingMacroMethodsTest.groovy[Examples (I)]
- https://github.com/bsideup/groovy-pattern-match/blob/master/src/test/groovy/ru/trylogic/groovy/pattern/PatternMatchingMacroMethodsTest.groovy[Examples (II)]

== Resources

- http://www.groovy-lang.org/semantics.html#_switch_case[Groovy official documentation on switch/case]
- https://github.com/mariogarcia/blog[The blog sources]