= Frege basics: File I/O
Janus Lynd
2016-03-29
:jbake-type: post
:jbake-status: published
:jbake-tags: frege, io, files
:idprefix:
:sources: ../../../../../../../sources/2016/03/frege-file-basic

=== Intro

All examples are based on `IO.fr` module functions. You can find them
https://github.com/Frege/frege/blob/master/frege/java/IO.fr[Here].

=== Reading

We'll be using the **openReader** function. It creates a
**BufferedReader** from a given file path in the form of a **String**.

[source, haskell]
----
openReader :: String -> IO BufferedReader
----

The first example reads a file getting a list of lines out of it:

[source, haskell]
----
include::{sources}/src/main/frege/files/Read.fr[tags=read1,indent=0]
----

Here you have a shorter version:

[source, haskell]
----
include::{sources}/src/main/frege/files/Read.fr[tags=read2,indent=0]
----

NOTE: Here we were using the placeholder notation `_.XXX` to
avoid creating intermediate values.

But bear in mind that if you give a wrong path the
function call will raise an error. Here is an example returning an
empty list in case the file doesn't exists.

[source, haskell]
----
include::{sources}/src/main/frege/files/Read.fr[tags=safer,indent=0]
----

=== Writing

As opposed to **openReader** there is a **openWriter** to write to a
file. The **openWriter** and **appendWriter** functions return a
**PrintWriter** instance. Lets see how can we use them. In the first
example I'm setting the content of a file.

[source, haskell]
----
include::{sources}/src/main/frege/files/Write.fr[tags=write1,indent=0]
----

<1> Getting the **PrintWriter** instance
<2> Writing to file
<3> Flushing to reflect the changes

IMPORTANT: flushing is important when writing to a file.

But most of the time we would like to append information to a
file. The following example does exactly that.

[source, haskell]
----
include::{sources}/src/main/frege/files/Write.fr[tags=write2,indent=0]
----

<1> Getting the **PrintWriter** instance
<2> Appending content to a file
<3> Flushing to reflect the changes