= Kubernetes: Installation
@marioggar
2018-05-05
:jbake-type: post
:jbake-status: published
:jbake-tags: kubernetes, devops
:idprefix:
:sources: ../../../../../../../sources/2018/05/kubernetes_installation

== Intro

I've been working with Docker containers for a while, even my
development environment has been **dockerized**, but apart from
creating and running Docker images, I haven't gone any further than
that. Nowadays containers are everywhere, and there're many products
for provisioning and orchestrating containers. I'd say that the most
important is https://kubernetes.io[Kubernetes].

"Kubernetes is an open-source system for automating deployment,
scaling, and management of containerized applications."
-- kubernetes.io

As a result I've created a Vagrant installation to ease the creation
of a Kubernetes cluster with `flannel` as a POD network and `metallb`
as load balancer. The source code can be found at **TODO**

== Structure

Before creating the cluster I need to create two virtual machines
(master + slave) and install the required libraries in order
Kubernetes to work. Because I'm using
https://www.vagrantup.com/[Vagrant] and
https://www.ansible.com/[Ansible] to create and provision master and
slave virtual machines, it's required to install both before going any
further.

=== Vagrant images

NOTE: For more information about Vagrant go to https://www.vagrantup.com/

For this POC I've created a couple of VMs with Vagrant to mimic
barebone machines.

[ditaa, "2018/05/kubernetes_installation/project-structure", "png", align=center, indent=0]
----
kubernetes-+
     +-----> Vagrantfile
     +-----> ansible
                |
                +----> roles/
                |
                +----> playbook-master.yml
                |
                +----> playbook-slave.yml
----

[source, ruby]
.Vagrantfile
----
include::{sources}/kubernetes/Vagrantfile[indent=0]
----

IMPORTANT: Make sure master and slave hostnames are different
otherwise Kubernetes won't show the slave machine when listing
available nodes.

IMPORTANT: Make sure you've installed the `vagrant-disksize` plugin
before building vagrant boxes: `vagrant plugin install
vagrant-disksize`

=== Ansible provisioning

NOTE: For more information about Ansible go to https://www.ansible.com/

The Vagrant files are using an Ansible playbook in order to install
the system requirements in order Kubernetes to work. Depending on
whether the node has been declared as master or slave it will make use
of one playbook or the other. Master playbook:

[source, yaml]
.master playbook
----
include::{sources}/kubernetes/ansible/playbook-master.yml[indent=0]
----

- Base libraries
- Kubernetes related libraries: kubeadm, kubectl...
- Kubernetes cluster initialization
- Kubernetes POD network installation
- Kubernetes MetalLB (Load Balancer) installation

And for the slave nodes:

[source, yaml]
.slave playbook
----
include::{sources}/kubernetes/ansible/playbook-slave.yml[indent=0]
----

- Base libraries
- Kubernetes related libraries: kubeadm, kubectl...
- Kubernetes slave node joins master node

== Installation

Go to the /kubernetes directory and execute:

[source, shell]
----
vagrant up
----

The process will prompt you in order to choose which network device
will be used as a bridged connection. Once the process has finished
you can log in the master vm:

[source, shell]
----
vagrant ssh sherlock
----

And make sure both nodes are up and ready:

[source, shell]
----
kubectl get nodes
----