= Kubernetes: Using MetalLB to expose a service
@marioggar
2018-05-06
:jbake-type: post
:jbake-status: published
:jbake-tags: kubernetes, devops
:idprefix:
:sources: ../../../../../../../sources/2018/05/kubernetes_02

== Intro

Once we have our Kubernetes cluster, it's time to deploy something in
it. I'm going to follow a simple deploying a Ratpack application I did
sometime ago and that I packed as a docker image at Bintray.

== Installing POD

=== Pod declaration

In the POD declaration I'm defining the Docker image url. And the port
where the application is exposed.

[source, yaml]
----
include::{sources}/pnlp-pod.yml[indent=0]
----

=== How to deploy my POD

[source, shell]
----
kubectl create -f pnlp-pod.yml
----

=== How to see deployed  POD details

If we want to see things like which private IP is the app exposed, we
can use:

[source, shell]
----
kubectl describe pods/pnlp-pod.yml
----

=== How to destroy my POD

In case we would like to terminate the POD:

[source, shell]
----
kubectl delete pods pnlp-pod.yml
----

== Installing service

We're using a `Load Balancer` to expose our service to a public IP.

=== MetalLB configuration

MetalLB is nowadays the only load balancer available for a barebone
Kubernetes solution. It will expose our application in the available
public IPs. In order to provide MetalLB with a range of available IPs
we can deploy a MetalLB configuration to Kubernetes like the
following:

IMPORTANT: I'm using my Vagrant Kubernetes image which already has
MetalLB installed and configured.

[source, yaml]
----
include::{sources}/metallb-config.yml[indent=0]
----

=== Service definition

Ok so we've already deployed our application but it's not publicly
available, it would be nice to publish it to the outside world. In order
to do that we need to define a service of type `LoadBalancer`.

[source, yaml]
----
include::{sources}/pnlp-service.yml[indent=0]
----

=== How to deploy service

[source, shell]
----
kubectl create -f pnlp-service.yml
----

=== Check where the service's been deployed ?

[source, shell]
----
kubectl get services
----