= Logic: Propositional logic
@marioggar
2018-12-16
:jbake-type: post
:jbake-status: published
:jbake-tags: cs, maths, algebra
:sources: ../../../../../../../sources/2018/12/logic
:idprefix:

"Logic will get you from A to B. Imagination will take you everywhere"
-- Albert Einstein

=== Intro

The use of logic helps us to establish the validity of a given
statement. It's important to notice that a logical statement doesn't
have to make any sense, it only has to be structured following certain
rules or formal steps.

There're two main types of logic systems, *propositional logic*, and
*predicate logic*. This article talks about the former. In a
propositional system, formal steps make use of *propositions*
connected with *logical operators*.

- *propositions*: things we want to assess. They can only be true or
   false.
- *Logical operators*: the way the former variables are related to
  each other.

=== Initial statement

[.text-center]
`IF THE NEXT PROJECT USES JAVA, THEN I'M IN`
 +
 +

The first thing we should do is to map the expression to
*propositions* or *logical variables*. Those are the parts of the
expression we want to evaluate. In this case we have:

* `A`: IF THE NEXT PROJECT USES JAVA
* `B`: THEN I'M IN

You can also say that the conditional statement has a *hypothesis*
(IF...) and a clause (I'm in). We can also notice the dependency
between both propositions. *A* implies that *B* can happen. This can
be expressed as:

[mathx, width=150, height=120]
----
A \implies B
----

=== Negation

We can also express just the opposite of a given *logical variable*,
with the negation operator:

* `!A`: IF THE NEXT PROJECT DOESN'T USE JAVA
* `!B`: THEN I'M NOT IN

NOTE: It's important to notice that here I'm using the `!` operator as
a conditional variable operator, that's because most of the time we
programmers use it to negate boolean expressions. However the
mathematical symbol of boolean negation is `&#x00AC;`.

=== Contrapositive

What if I would like to represent the same statement in a negative
way:

[.text-center]
`IF THE NEXT PROJECT DOESN'T USE JAVA, THEN I'M OUT`
 +
 +

This would imply that I didn't join the project, because the next
project is not using Java.

[mathx, width=150, height=120]
----
\neg A \implies \neg B
----

This is the *contrapositive* version of our initial statement. This
means that both try to express the same thing but from different
perspectives, positive and negative. Every conditional expression has
its contrapositive equivalent. In mathematical syntax:

[mathx, width=300, height=120]
----
A \implies B = \neg A \implies \neg B
----

=== Biconditional

Lets remind our initial propositional sentence: *IF THE NEXT PROJECT
USES JAVA, THEN I'M IN*. What if I also say:

[.text-center]
`IF THE NEXT PROJECT USE PYTHON, THEN I'M I'M`
 +
 +

Am I saying something contradictory to the previous sentence ? Not at
all. I could be interested in a project using Python or Java. So if I
wanted to be very explicit about the fact that I'm willing to do the
next project *only if* Java is on the table, then I have to express
the statement using the biconditional operator.

[mathx, width=150, height=120]
----
A \iff B
----

This expression now reflects that:

[.text-center]
`IF, AND ONLY IF THE NEXT PROJECT USE JAVA, THEN I'M IN`
 +
 +

So now you've narrowed the posibilities of interpretation of your
initial proposition.

=== References

- http://mfleck.cs.illinois.edu/building-blocks/[Building Blocks for Theoretical of Computer Science] by Margaret M. Fleck
- https://pragprog.com/book/mcmath/good-math[Good Maths] by Mark C. Chu-Carroll
- https://code.energy/computer-science-distilled[Computer Science Distilled] by Wladston Ferreira Filno