= Logic
@marioggar
2018-11-10
:jbake-type: post
:jbake-status: published
:jbake-tags: cs, maths, algebra
:sources: ../../../../../../../sources/2018/12/logic
:idprefix:

=== Intro

The use of logic help us to establish the validity of a given
statement. In order to achieve that, we may know to make use of the
`logical operators` and map correctly the things we want to asses to
`logical variables`.

=== First example

[.text-center]
IF THE NEXT PROJECT USES JAVA, I'M IN
 +
 +

The first thing we should do is to map the expression to `logical
variables`. Those are the parts of the expression we want to
evaluate. In this case we have:

* A: IF THE NEXT PROJECT USES JAVA
* B: I'M IN

You can also say that the conditional statement has a `hypothesis`
(IF...) and a clause (I'm in). We can also notice the dependency
between both variables. *A* implies that *B* can happen. This can be
expressed as:

[mathx, width=150, height=120]
----
A \implies B
----

=== Negation

We can also express just the opposite of a given `logical variable`,
with the negation operator:

* !A: IF THE NEXT PROJECT DOESN'T USE JAVA
* !B: I'M NOT IN

=== Contrapositive

If I'd like to represent the situation where I the next project didn't
use Java. That automatically implies that I didn't join the project.

[mathx, width=300, height=200]
----
A \implies B = \neg A \implies \neg B
----

As bottom line bear in mind that every conditional expression has its
contrapositive equivalent.