= Propositional logic: exercises
@marioggar
2018-12-22
:jbake-type: post
:jbake-status: published
:jbake-tags: cs, logic
:sources: ../../../../../../../sources/2018/12/logic_exercises
:idprefix:
:summary: Some basic and simple exercises to train propositional logic.

=== Exercises

Some exercises to train propositional logic.

NOTE: If anyone sees an error please raise an issue in the blog
repository, thanks :).

==== Exercise 1

Let's consider a *propositional language* where:

- `p`: Is Monday
- `q`: John goes running
- `r`: Elsa goes running

Formalize the following sentences:

"If it's Monday, John and Elsa go running"
-- A

"If it's Monday John goes running"
-- B

"If it's other day than Monday, Elsa goes running, but John doesn't"
-- C

*Solutions*:

[mathx, height=50]
.A
----
p \implies q \land r
----

[mathx, height=50]
.B
----
p \implies q
----

[mathx, height=50]
.C
----
\neg p \implies r \land \neg q
----

*Table of truth*

[mathx, width=450]
----
\begin{tabular}{cc|c|c}
q & r & p \implies q \land r & \neg p \implies \neg q \land r \\
\hline
T & T & T & F \\
F & T & F & T \\
T & F & F & F \\
F & F & F & F \\
\end{tabular}
----

==== Exercise 2

Let's consider a *propositional language* where:

- `p`: John buys lottery tickets
- `q`: Is Christmas time
- `r`: John feels lucky

Formalize the following sentences:

"If is Christmas time, or John feels lucky, then John buys lottery
tickets"
-- A

"If it's not Christmas, and John doesn't feel lucky, he doesn't buy
lottery"
-- B

*Solutions*:

[mathx, height=50]
.A
----
p \implies q \lor r
----

[mathx, height=50]
.B
----
\neg p \implies \neg q \land \neg r
----

*Table of truth*

[mathx, width=450]
----
\begin{tabular}{cc|c|c}
q & r &  p \implies q \lor r &  \neg p \implies \neg q \land \neg r \\
\hline
T & T & T & F \\
F & T & T & F \\
T & F & T & F \\
F & F & F & T \\
\end{tabular}
----